using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VPMS.Persistence.Migrations
{
    public partial class addadminuserautogeneratedusertosuperadminrole : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "AspNetUserRoles",
                columns: new[] { "RoleId", "UserId" },
                values: new object[] { new Guid("e24f4cd1-0759-440e-9a2b-6072880392b6"), new Guid("b74ddd14-6340-4840-95c2-db12554843e5") });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "AspNetUserRoles",
                keyColumns: new[] { "RoleId", "UserId" },
                keyValues: new object[] { new Guid("e24f4cd1-0759-440e-9a2b-6072880392b6"), new Guid("b74ddd14-6340-4840-95c2-db12554843e5") });
        }
    }
}
